README.md

The usernames and details of the team members have been added to the readme.

Fix issue update readme

---

users/package-lock.json

Deleted file `package-lock.json` from directory `/users` (issue #3 )

Deleted file package-lock.json from /users directory (issue #3)

---

docs/src/03_context_and_scope.adoc

Added context section to documentation, with 2 tables and 2 uml diagrams.

Issue#9 Add context to Documentation

---

docs/src/01_introduction_and_goals.adoc

This pull request includes changes to the `docs/src/01_introduction_and_goals.adoc` file to update the table of roles, contacts, and expectations. The changes involve modifying the table's columns and adding detailed information about various roles and their expectations.
Changes to the table structure and content:
* Updated the table column configuration from "1,2,2" to "1,1,1" to ensure uniform column widths.
* Added specific roles such as `RTVE`, `ChattySw`, `Professors`, `Application Users`, and `Development Team` along with their respective contacts and detailed expectations.

Issue#8 Add stakeholders to Documentation

---

docs/src/02_architecture_constraints.adoc

Wrote documentation for the project conventions and constraints

Add documentation for the project constraints

---

docs/src/04_solution_strategy.adoc

Wrote documentation for the project technologies

add technologies to documentation

---

docs/src/10_quality_requirements.adoc

Add quality requirements to documentation (Section 10)

Issue#30 quality requirements

---

docs/src/09_architecture_decisions.adoc
docs/src/10_quality_requirements.adoc

Add architecture decisions to documentation (section 9).

Issue#29 arch decisions

---

docs/src/11_technical_risks.adoc

Wrote documentation for section 11, risks and technical debts. Issue #31

31 write documentation for the risks and technical debts

---

docs/src/07_deployment_view.adoc

Add documentation for deployment information & deployment view

---

docs/src/04_solution_strategy.adoc

fix solution strategy documentation

---

docs/src/06_runtime_view.adoc

Wrote documentation for the running view. Issue #26

Wrote documentation for the runtime view part

---

docs/src/06_runtime_view.adoc

Fixed bug and improve uml

---

.github/workflows/release.yml
.vscode/settings.json
README.md
docker-compose.yml
llmservice/.dockerignore
llmservice/llm-service.js
llmservice/llm-service.test.js
llmservice/package-lock.json
llmservice/package.json
webapp/Dockerfile
webapp/src/App.js
webapp/src/components/Login.js

Fixed the leak of the API key applying changes performed by https://github.com/Arquisoft/wichat_0/pull/45.
This pull requests closes https://github.com/Arquisoft/wichat_en1b/issues/59.

Issue#59-fix-api-key-exposure

---

docs/src/06_runtime_view.adoc

Fixed diagrams for the Runtime View section.
Changes added:
- **Fixed** Sign Up Flow
- **Fixed** Log In Flow
- **Fixed** Quiz Question Retrieval Flow
- **Fixed** LLM Chat Interaction Flow
- **Removed** Error Handling Scenario
- **Added** Question Game Interaction Flow
- **Added** Statistics Interaction Flow

56 fix runtime view

---

questionservice/.dockerignore
questionservice/package-lock.json
questionservice/package.json
questionservice/quest-service.js

This pr is linked with the sub-issue #76 
Question service basic module is created and it generates a server using express in the port 8004

Question service created, listens in port 8004

---

docs/src/02_architecture_constraints.adoc

Fixed Architecture Constraints documentation section (Issue #55) according
to the [03 - Minutes Session](https://github.com/Arquisoft/wichat_en1b/wiki/03-%E2%80%90-Minutes-Session)

55 fix technical constraints

---

docs/src/06_runtime_view.adoc

Added `end` tag in LLM Chat Interaction Flow diagram. 
Issue #80

Fixed bug in LLM Chat Interaction Flow diagram introduced in pr #72

---

docs/src/09_architecture_decisions.adoc

Changed in AD-001 from Typescript to Javascript according to the [meeting 03](https://github.com/Arquisoft/wichat_en1b/wiki/03-%E2%80%90-Minutes-Session)

Fixed architecture decisions in documentation

---

docs/src/03_context_and_scope.adoc

Changed Technical Context diagram from 3D to 2D for better comprehension.

fix context & scope diagram documentation

---

.github/workflows/build.yml
.github/workflows/release.yml
questionservice/package-lock.json
questionservice/package.json
questionservice/quest-service.test.js

- `build.yml`
- `release.yml`
According to issue #88

Updated build.yml and release.yml to add the question service microservice to the Github Actions

---

docs/src/01_introduction_and_goals.adoc

Added empathy as stakeholder in the documentation.

New stakeholders

---

statisticservice/statistics-service.js
statisticservice/statistics-service.test.js

Minor change on previous statistics service (error 404 instead of 401 for not found user). 
Added new POST method that updates user's statistics (intended to be called at the end of a game).
New test cases for new logic.

Functional statistics service.

---

questionservice/controllers/WikidataController.js
questionservice/package-lock.json
questionservice/package.json
questionservice/quest-service.js

#92 First prototype accessing Wikidata API

first wikidata fetching prototype

---

gatewayservice/gateway-service.js
gatewayservice/gateway-service.test.js
questionservice/controllers/WikidataController.js
questionservice/controllers/questionTypes.js
questionservice/quest-model.js
questionservice/quest-service.js
users/authservice/auth-service.test.js

Increase and improve question service funcionality

---

docs/src/07_deployment_view.adoc

fix deployment view diagrams

---

docker-compose.yml
webapp/Dockerfile

This pull request fixed a problem generated in #141 due to bad actions when reloading containers under the watch functionality. This has been [commented](https://github.com/Arquisoft/wichat_en1b/issues/140#issuecomment-2735835575) in #140 and solved now.

Fixed a context error when reloading containers

---

gatewayservice/gateway-service.js
gatewayservice/gateway-service.test.js

deletion of repeated method in gateway service.

Enhancement of tests in gateway service and

---

gatewayservice/gateway-service.js
gatewayservice/gateway-service.test.js
gatewayservice/openapi.yaml
llmservice/llm-service.js
llmservice/llm-service.test.js
questionservice/quest-service.js
statisticservice/statistics-service.js
statisticservice/statistics-service.test.js
users/authservice/auth-service.js
users/userservice/user-service.js
webapp/src/components/Game/Question/Question.js

Included documentation for all the endpoints of the application. Also I modified some of the request codes that are more  appropiate and eliminated a duplicated reference to checkQuestion.

154 documentation for all the endpoints of the gatewayservice

---

README.md

Updated the `README.md` file to comply with the project status.

153 update readmemd file

---

webapp/package-lock.json
webapp/package.json
webapp/src/components/Home/Home.js

Added a logo to the homepage. This logo will show when the user is not logged in. It has an animation simulating that it's floating. Solves issue #168

168 create a nicer home page

---

docker-compose.yml

Just a tiny fix so deployment machine can work properly.

Fixed lack of env_file on some services

---

package-lock.json
package.json
webapp/src/App.test.js
webapp/src/components/Game/Chat/Chat.js
webapp/src/components/Game/Chat/Chat.test.js
webapp/src/components/Game/Question/Question.test.js
webapp/src/components/Home/Home.test.js
webapp/src/components/LogInSignUp/Login.test.js
webapp/src/components/LogInSignUp/SignUp.test.js

Fixed some tests for the frontend components. Missing some tests for the Chat

Fixed Frontend tests

---

docs/src/01_introduction_and_goals.adoc
docs/src/02_architecture_constraints.adoc
docs/src/05_building_block_view.adoc
docs/src/07_deployment_view.adoc
docs/src/08_concepts.adoc
docs/src/13_annex.adoc

This PR includes some changes in the documentation of the project to comply with the current application status.

Project documentation

---

gatewayservice/gateway-service.js
gatewayservice/gateway-service.test.js
statisticservice/statistics-service.js
statisticservice/statistics-service.test.js
webapp/package-lock.json
webapp/package.json
webapp/src/components/Statistics/RecordRetriever.js
webapp/src/components/Statistics/Statistics.js
webapp/src/components/Statistics/Statistics.test.js
webapp/src/components/Statistics/components/ErrorMessage.jsx
webapp/src/components/Statistics/components/LoadingSpinner.jsx
webapp/src/components/Statistics/components/StatisticsFilter.jsx
webapp/src/components/Statistics/components/StatisticsTable.jsx
webapp/src/components/Statistics/theme.css

View for leaderboards, showing statistics.
Will change statistics GET endpoints so that:
- /statistics/:username: Retrieves the statistics for the user specified _(old /statistics logic)_
- /statistics: Retrieves ordered statistics of all users stored in the system _(new endpoint)_

193 leaderboard view

---

gatewayservice/openapi.yaml
questionservice/controllers/WikidataController.js
questionservice/models/answer-model.js
questionservice/quest-service.js
questionservice/repositories/AnswerRepository.js
questionservice/repositories/QuestionRepository.js
webapp/public/locales/ast.json
webapp/public/locales/de.json
webapp/public/locales/en.json
webapp/public/locales/es.json
webapp/public/locales/fr.json
webapp/src/App.js
webapp/src/components/Game/Chat/Chat.js
webapp/src/components/Game/Question/GameEndScreen.js
webapp/src/components/Game/Question/Question.js
webapp/src/components/Game/components/StatisticsUpdater.js
webapp/src/components/hooks/useAuth.js
webapp/src/components/layouts/ProtectedLayout.js

- Fixes #247 - Minor cookie handling bug.
- Closes #232 - Frontend for question of the day, only allowing 1 answer per user and with correct feedback.
- Improvements to colors when answering questions.
- React router code cleanup.
- Show correct option to user when answer is wrong.

Question of the day + improvements

---

statisticservice/statistics-service.js
webapp/public/locales/ast.json
webapp/public/locales/de.json
webapp/public/locales/en.json
webapp/public/locales/es.json
webapp/public/locales/fr.json
webapp/src/components/Game/Chat/Chat.js
webapp/src/components/Game/GameContext.js
webapp/src/components/Game/Question/Question.js
webapp/src/components/Profile/Profile.js
webapp/src/components/Profile/components/AdditionalInsights.jsx
webapp/src/components/Profile/components/Insights.js
webapp/src/components/fragments/Navbar.js

This pull request fix bug #252 and introduce changes on the statistics shown in the profile view from issue #251

Fixed bug. Chat now clears the messages at the end of the round

---

webapp/src/components/Game/GameContext.js
webapp/src/components/Game/Question/Question.js
webapp/src/components/Game/Question/Question.test.js
webapp/src/components/hooks/useRounds.js
webapp/src/components/hooks/useTimer.js
webapp/src/components/hooks/useTimer.test.js

fix time up functionality
